### ISSUE TITLE
关于dnc的一些疑问

### ISSUE THREAD

**Issue by EzrealJ** [dncNew/dncNew#5]

**Comment by Anduin2017** [comment]
我认为这里既然是开源社区，更恰当的是在这里列举出一些使用了.NET Core作为核心框架的著名开源项目；仅仅列举一些公司而不举出案例在这里并不是很合适，展现略显生硬。建议将这些内容发布到其它地方，例如博客园、微信公众平台，宣传效果会更好。

个人一点建议。

**Comment by dncNewAdmin** [comment]
@EzrealJ  

文章中有专门提到

dnc = .NET Core、dotnet Core 简称
sf = Service Fabric  简称

简称只是各自的习惯用法，主要为了方便快速打字输入与沟通，每个人习惯的简称可能不一定一样，只要互相之间能沟通理解就行，不存在对错，互相尊重各自的习惯

dn
dnc
.net core
dotnet core
asp.net core
asp.net core mvc
asp.net core webapi
php
go
c

上面提到的dnc开源项目列表，就是自己收集的一些国内外知名的.NET Core开源项目列表，分享出来给需要的人，收集整理开源信息，不代表 这些整理的信息与开源项目 是 收集者 自己开发的，文章中也有专门提到 需要到各个开源项目官网查看开源协议与版权归属，尊重开源知识产权

例如JS开源项目Vue 与 JavaScript开源项目Vue 是一个含义，

可能目前dnc的简称还没有像JS这样流行，造成了一些误会，请见谅

群里有一些朋友反馈，刚开始可能不太习惯dnc简称，打字次数多了之后，感觉比较方便，也不影响信息沟通
